railsServer/config/routes.rb
Rails.application.routes.draw do
  resources :videos
  resources :sensors do 
  	resources :values
  end 
  	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

railsServer/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

railsServer/app/models/sensor.rb
class Sensor < ApplicationRecord
	has_many :values, dependent: :destroy 
end

railsServer/app/models/video.rb
class Video < ApplicationRecord
	has_one_attached :clip
	has_one_attached :thumbnail
end

railsServer/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

railsServer/app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  before_action :set_sensor, only: [:show, :edit, :update, :destroy]

  # GET /sensors
  # GET /sensors.json
  def index
    @sensors = Sensor.all
  end

  # GET /sensors/1
  # GET /sensors/1.json
  def show
    @values = Value.where(sensor_id: @sensor)
  end

  # GET /sensors/new
  def new
    @sensor = Sensor.new
  end

  # GET /sensors/1/edit
  def edit
  end

  # POST /sensors
  # POST /sensors.json
  def create
    @sensor = Sensor.new(sensor_params)

    respond_to do |format|
      if @sensor.save
        format.html { redirect_to @sensor, notice: 'Sensor was successfully created.' }
        format.json { render :show, status: :created, location: @sensor }
      else
        format.html { render :new }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sensors/1
  # PATCH/PUT /sensors/1.json
  def update
    print "testing!!!!"
    respond_to do |format|
      if @sensor.update(sensor_params)
        format.html { redirect_to @sensor, notice: 'Sensor was successfully updated.' }
        format.json { render :show, status: :ok, location: @sensor }
        format.js # render values 
      else
        format.html { render :edit }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sensors/1
  # DELETE /sensors/1.json
  def destroy
    @sensor.destroy
    respond_to do |format|
      format.html { redirect_to sensors_url, notice: 'Sensor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sensor
      @sensor = Sensor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sensor_params
      params.require(:sensor).permit(:name, :value)
    end
end

railsServer/app/controllers/values_controller.rb
class ValuesController < ApplicationController
	before_action :find_sensor

	def create 
		@value = @sensor.values.create(value_params)
		respond_to do |format|
			if @value.save
				format.html { redirect_to @sensor, notice: 'Value was successfully created.' }
				format.json { render :show, status: :created, location: @sensor }
			else
				format.html { render :new }
				format.json { render json: @sensor.errors, status: :unprocessable_entity }
			end
		end
	end 
	
	private 
	# Find the sensor for the values recived 
	def find_sensor 
		@sensor = Sensor.find(params[:sensor_id])
	end 
	# Never trust parameters from the scary internet, only allow the white list through.
	def value_params
		params.require(:value).permit(:json)
	end
end

railsServer/app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:title, :description, :flag,:clip,:thumbnail)
    end
end

railsServer/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

railsServer/app/helpers/application_helper.rb
module ApplicationHelper
end

railsServer/app/helpers/sensors_helper.rb
module SensorsHelper
end

railsServer/app/helpers/values_helper.rb
module ValuesHelper
end

railsServer/app/helpers/videos_helper.rb
module VideosHelper
end

railsServer/app/helpers/welcome_helper.rb
module WelcomeHelper
end

railsServer/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="generator" content="Jekyll v3.8.6">
  <title>CarblackboxServer</title>
  
  
</head>
<body>
  <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="<%= root_path %>"><span class="fe fe-codesandbox"></span><b>IOT</b>BlackBox</a>
  
    <ul class="navbar-nav px-3 form-control-dark w-100">
    </ul>
  </nav>

  <div class="container-fluid">
    <div class="row">
      <%= render partial: "shared/nav" %>

      <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
        <%= yield %>
      </main>
    </div>
  </div>
  
</body>
</html>

railsServer/app/views/sensors/_form.html.erb
<%= form_with(model: sensor, local: true) do |form| %>
  <% if sensor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sensor.errors.count, "error") %> prohibited this sensor from being saved:</h2>

      <ul>
      <% sensor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

railsServer/app/views/sensors/edit.html.erb
<h1>Editing Sensor</h1>

<%= render 'form', sensor: @sensor %>

<%= link_to 'Show', @sensor %> |
<%= link_to 'Back', sensors_path %>

railsServer/app/views/sensors/index.html.erb
<%= render partial: "shared/header", locals: {title: "Sensors" , back: root_path,single_page: ""} %>

<p id="notice"><%= notice %></p>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">values recived</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sensors.each do |sensor| %>
      <tr>
        <td scope="row"><%= sensor.name %></td>
        <td scope="row"><%= sensor.values.count %></td>
        <td scope="row"><%= link_to 'Show', sensor, :class => "btn btn-secondary" %></td>
        <td scope="row"><%= link_to 'Edit', edit_sensor_path(sensor), :class => "btn btn-secondary" %></td>
        <td scope="row"><%= link_to 'Destroy', sensor, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-secondary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'New Sensor', new_sensor_path, :class => "btn btn-primary" %>

railsServer/app/views/sensors/new.html.erb
<h1>New Sensor</h1>

<%= render 'form', sensor: @sensor %>

<%= link_to 'Back', sensors_path %>

railsServer/app/views/sensors/show.html.erb
<%= render partial: "shared/single_header", locals: {title: @sensor.name , back: sensors_path, edit_page:edit_sensor_path(@sensor) } %>
<div id="info">
	<p id="notice"><%= notice %></p>

	<p>
		<strong>Name:</strong>
		<%= @sensor.name %>
	</p>
	<canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas>
	<table class="table table-striped">
		<thead>
			<tr>
				
				<th scope="col">JSON</th>
				<th scope="col">Create AT</th>
			</tr>
		</thead>

		<tbody>
			<% @sensor.values.each do |value| %>
			<tr>
				<td><%= value.json %></td>
				<td><%= value.created_at %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
	<%= render "values/form" %>


</div>

<script type="text/javascript">
	/* globals Chart:false, feather:false */

	(function () {
		'use strict'

  // Graphs
  var ctx = document.getElementById('myChart')
  // eslint-disable-next-line no-unused-vars
  var myChart = new Chart(ctx, {
  	type: 'line',
  	data: {
  		labels: [
  		<% @values.each do |value| %>
  		"<%= value.created_at.to_date %>",
  		<% end %>
  		],
  		datasets: [{
  			data: [
  			<% @sensor.values.each do |value| %>
  			<%= value.json %>,
  			<% end %>
  			],
  			lineTension: 0,
  			backgroundColor: 'transparent',
  			borderColor: '#007bff',
  			borderWidth: 4,
  			pointBackgroundColor: '#007bff'
  		}]
  	},
  	options: {
  		scales: {
  			yAxes: [{
  				ticks: {
  					beginAtZero: false
  				}
  			}]
  		},
  		legend: {
  			display: false
  		}
  	}
  })
}())
</script>

railsServer/app/views/shared/_header.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">

	<h1 class="h2"><%= title %></h1>
	<div class="btn-toolbar mb-2 mb-md-0">
		<div class="btn-group mr-2">
			<% if back.present? and not(back.nil?) then %>
			
			
			<%= link_to 'Back', back , :class => "btn btn-sm btn-outline-secondary" %>
			<% end -%>

			<% if single_page.present? and not(single_page.nil?) then %>
			
				<%= link_to 'Show', single_page, :class => "btn btn-sm btn-outline-secondary" %> 
			<% end -%>
		</div>
	</div>
</div>

railsServer/app/views/shared/_nav.erb
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
  <div class="sidebar-sticky">
    <ul class="nav flex-column">

      <li class="nav-item">
        <a class="nav-link <% if @sensors.present? then %>
          active
          <% end %>" href="<%= sensors_path %>">
          <span class="fe fe-home"></span>
          Sensors <span class="sr-hard-drive"></span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link <% if @videos.present? then %>
          active
          <% end %>" href="<%= videos_path %>">
          <span class="fe fe-video"></span>
          Videos
        </a>
      </li>
    </ul>

    <!-- <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
      <span>Saved reports</span>
      <a class="d-flex align-items-center text-muted" href="#" aria-label="Add a new report">
        <span class="fe fe-plus"></span>
      </a>
    </h6> -->
    <ul class="nav flex-column mb-2">
    </ul>
  </div>
</nav>

railsServer/app/views/shared/_single_header.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">

	<h1 class="h2"><%= title %></h1>
	<div class="btn-toolbar mb-2 mb-md-0">
		<div class="btn-group mr-2">
			
			
			

			<% if edit_page.present? and not(edit_page.nil?) then %>
			
				<%= link_to 'edit', edit_page, :class => "btn btn-sm btn-outline-secondary" %> 
			<% end -%>
			<% if back.present? and not(back.nil?) then %>
				<%= link_to 'Back', back , :class => "btn btn-sm btn-outline-secondary" %>
			<% end -%>
		</div>
	</div>
</div>

railsServer/app/views/videos/_form.html.erb
<%= form_with(model: video, local: true) do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title,:class =>"form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :thumbnail %>
    <%= form.file_field :thumbnail,:class =>"form-control-file" %>
  </div>

  <div class="form-group">
    <%= form.label :clip %>
    <%= form.file_field :clip,:class =>"form-control-file" %>
  </div>

  <div class="form-group">
    <%= form.label :description%>
    <%= form.text_area :description,:class =>"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :flag%>
    <%= form.text_field :flag,:class =>"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit 'submit',:class =>"btn btn-primary" %>
  </div>
<% end %>

railsServer/app/views/videos/edit.html.erb
<%= render partial: "shared/header", locals: {title: "Editing Video" , back: videos_path, single_page: @video} %>

<%= render 'form', video: @video %>

railsServer/app/views/videos/index.html.erb
<%= render partial: "shared/header", locals: {title: "Videos" , back: root_path,single_page: ""} %>
<p id="notice"><%= notice %></p>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Flag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.title %></td>
        <td><%= video.description %></td>
        <td><%= video.flag %></td>
        <td><%= link_to 'Show', video, :class => "btn btn-secondary" %></td>
        <td><%= link_to 'Edit', edit_video_path(video), :class => "btn btn-secondary" %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } , :class => "btn btn-secondary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path, :class => "btn btn-primary" %>

railsServer/app/views/videos/new.html.erb
<%= render partial: "shared/header", locals: {title: "New Video" , back: videos_path ,single_page: ""} %>
<%= render 'form', video: @video %>

railsServer/app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @video.title %>
</p>
<div style="width: 400px; height: 400px">
	<%= image_tag(@video.thumbnail, style:'width:100%; height:auto') %>
</div>
<div style="width: 400px; height: 400px">
	<%= video_tag(url_for(@video.clip), style:'width:100%; height:auto', controls:'')%>
</div>

<p>
  <strong>Description:</strong>
  <%= @video.description %>
</p>

<p>
  <strong>Flag:</strong>
  <%= @video.flag %>
</p>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>