config/routes.rb
Rails.application.routes.draw do



  resources :contacts
  resources :streams
  resources :maps do
    get 'current', on: :collection
  end

  resources :videos

  resources :sensors do
   resources :values do
     get 'current', on: :collection
   end
  end

  resources :sensor_types do
    resources :sensors do
  	 resources :values
    end
  end

  #devise routes
  devise_for :users

  # root route
  root 'welcome#index'
end

app/models/map.rb
class Map < ApplicationRecord
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :set_map, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /maps
  # GET /maps.json
  def index

    @maps = Map.paginate(:page => params[:page], :per_page => 200).order(id: :desc)
    @bootstrap_paginate_renderer = bootstrap_paginate_renderer
  end
  
  #  GET /maps/current
  #  GET /maps/current.json
  def current
    @map = Map.last
  end
  # GET /maps/1
  # GET /maps/1.json
  def show
  end

  # GET /maps/new
  def new
    @map = Map.new
  end

  # GET /maps/1/edit
  def edit
  end

  # POST /maps
  # POST /maps.json
  def create
    @map = Map.new(map_params)
    respond_to do |format|
      if @map.save
        format.html { redirect_to @map, notice: 'Map was successfully created.' }
        format.json { render :show, status: :created, location: @map }
      else
        format.html { render :new }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maps/1
  # PATCH/PUT /maps/1.json
  def update
    respond_to do |format|
      if @map.update(map_params)
        format.html { redirect_to @map, notice: 'Map was successfully updated.' }
        format.json { render :show, status: :ok, location: @map }
      else
        format.html { render :edit }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.json
  def destroy
    @map.destroy
    respond_to do |format|
      format.html { redirect_to maps_url, notice: 'Map was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_map
      @map = Map.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def map_params
      params.require(:map).permit(:time, :lat, :lon, :alt, :quality, :satellites, :hdop, :geoidal, :age, :stationID, :raw, :valid, :type)
    end
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/maps/current.html.erb
<%= render partial: "shared/header", locals: {title: "LIVE MAP" , back: maps_path ,single_page: ""} %>
<p id="notice"><%= notice %></p>
<div id="map" class="map">
  <!-- OL map will be here  -->
</div>


<script type="text/javascript">
	// adding GPS DATA
	window.currentUrl = "current.json";
	window.geojsonObject =  {
	  'type': 'FeatureCollection',
	  'crs': {
	    'type': 'name',
	    'properties': {
	      'name': 'EPSG:3857'
	    }
	  },
	  'features': [
		<% if(Map.any?) then %>
		{
	    'type': 'Feature',
	    'geometry': {
	      'type': 'Point',
	      'coordinates': ol.proj.fromLonLat([
        <%= Map.last.lon %>
        ,
        <%= Map.last.lat %>
        ])
	    }
	  }
		<% end %>
		]
	};

	</script>

app/views/maps/index.html.erb
<%= render partial: "shared/header", locals: {title: "Maps" , back: root_path,single_page: ""} %>


<div class="d-flex justify-content-between row mx-1">
    <div>
        <a href="<%= maps_path + "/current"%>" class="btn btn-sm btn-outline-primary">Go to Live Map</a>
    </div>
    <div>
      <% if (not @maps.last.time.nil?) and (not @maps.first.time.nil?) then %>
        <small> <b>FROM:</b>  <%= @maps.last.time.to_datetime.strftime("%m/%d/%Y at %I:%M%p") %> </small>
        <small> <b>TO:</b>  <%= @maps.first.time.to_datetime.strftime("%m/%d/%Y at %I:%M%p") %> </small>
      <% end %>
    </div>
</div>


<div id="map" class="map my-4">
  <!-- OL map will be here  -->
</div>

<nav aria-label="Page navigation example">
  <ul class="pagination">
  <%= will_paginate @maps, renderer: @bootstrap_paginate_renderer %>
  </ul>
</nav>

<script type="text/javascript">

	// adding GPS DATA
	window.geojsonObject =  {
	  'type': 'FeatureCollection',
	  'crs': {
	    'type': 'name',
	    'properties': {
	      'name': 'EPSG:3857'
	    }
	  },
	  'features': [
		<% if(Map.any?) then %>
		{
	    'type': 'Feature',
	    'geometry': {
	      'type': 'Point',
	      'coordinates': ol.proj.fromLonLat([
        <%= @maps.first.lon %>
        ,
        <%= @maps.first.lat %>
        ])
	    }
	  },
		<% end %>
		{
	    'type': 'Feature',
	    'geometry': {
	      'type': 'LineString',
	      'coordinates': [
				<% @maps.each do |map| %>
					ol.proj.fromLonLat([
			        <%= map.lon %>
			        ,
			        <%= map.lat %>
					]),
					<% end %>
			]
	    }
	  }


		]
	};
  </script>

app/views/maps/show.html.erb
<%= render partial: "shared/single_header", locals: {title: @map.time , back: maps_path, edit_page:"" } %>

<p>
  <strong>Time:</strong>
  <%= @map.time %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @map.lat %>
</p>

<p>
  <strong>Lon:</strong>
  <%= @map.lon %>
</p>

<p>
  <strong>Alt:</strong>
  <%= @map.alt %>
</p>

<p>
  <strong>Quality:</strong>
  <%= @map.quality %>
</p>

<p>
  <strong>Satellites:</strong>
  <%= @map.satellites %>
</p>

<p>
  <strong>Hdop:</strong>
  <%= @map.hdop %>
</p>

<p>
  <strong>Geoidal:</strong>
  <%= @map.geoidal %>
</p>

<p>
  <strong>Age:</strong>
  <%= @map.age %>
</p>

<p>
  <strong>Stationid:</strong>
  <%= @map.stationID %>
</p>

<p>
  <strong>Raw:</strong>
  <%= @map.raw %>
</p>

<p>
  <strong>Is valid:</strong>
  <%= @map.is_valid %>
</p>

<p>
  <strong>Type:</strong>
  <%= @map.gps_type %>
</p>

<%= link_to 'Edit', edit_map_path(@map) %> |
<%= link_to 'Back', maps_path %>