config/routes.rb
Rails.application.routes.draw do



  resources :contacts
  resources :streams
  resources :maps do
    get 'current', on: :collection
  end

  resources :videos

  resources :sensors do
   resources :values do
     get 'current', on: :collection
   end
  end

  resources :sensor_types do
    resources :sensors do
  	 resources :values
    end
  end

  #devise routes
  devise_for :users

  # root route
  root 'welcome#index'
end

app/views/shared/_header.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">

	<h1 class="h2"><%= title %></h1>
	<div class="btn-toolbar mb-2 mb-md-0">
		<div class="btn-group mr-2">
			<% if back.present? and not(back.nil?) then %>
				<%= link_to 'Back', back , :class => "btn btn-sm btn-outline-secondary" %>
			<% end -%>

			<% if single_page.present? and not(single_page.nil?) then %>
				<%= link_to 'Show', single_page, :class => "btn btn-sm btn-outline-secondary" %>
			<% end -%>
			<% begin %>
					<% if new_page.present? and not(new_page.nil?) then %>
						<%= link_to 'Create New', new_page, :class => "btn btn-sm btn-outline-primary" %>
					<% end -%>
			<% rescue Exception => e %>
			<% end %>
		</div>
	</div>
</div>

app/views/shared/_nav.erb
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
  <div class="sidebar-sticky">
    <ul class="nav flex-column">
      <li class="nav-item">
        <a class="nav-link <% if current_page?(root_url)  then %>
          active
          <% end %>" href="<%= root_path %>">
          <span class="fe fe-activity"></span>
          Dashboard
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link <% if @sensors.present? then %>
          active
          <% end %>" href="<%= sensors_path %>">
          <span class="fe fe-bell"></span>
          Sensors <span class="sr-hard-drive"></span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link <% if @videos.present? then %>
          active
          <% end %>" href="<%= videos_path %>">
          <span class="fe fe-video"></span>
          Footage
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link <% if current_page?(maps_path) then %>
          active
          <% end %>" href="<%= maps_path %>">
          <span class="fe fe-map"></span>
          Maps
        </a>
      </li>
    </ul>

    <!-- <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
      <span>Saved reports</span>
      <a class="d-flex align-items-center text-muted" href="#" aria-label="Add a new report">
        <span class="fe fe-plus"></span>
      </a>
    </h6> -->
    <ul class="nav flex-column mb-2">
    </ul>
  </div>
</nav>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mx-0 p-0" style="z-index:1000;"">
  <a href="<%= root_path %>" class="btn btn-primary p-2 m-2" >IOT BlackBox</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-between" id="navbarNavDropdown">
    <ul class="navbar-nav">
    <% if user_signed_in? %>

      <li class="nav-item active">
        <a class="nav-link" href="<%= root_path %>">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= sensors_path %>">Sensors</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= contacts_path %>">Contacts</a>
      </li>
      <li class="nav-item">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownFootage" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Footage
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownFootage">
            <a class="dropdown-item" href="<%= videos_path %>"><span class="fe fe-folder"></span> recorded</a>
            <a class="dropdown-item" href="<%= streams_path %>"><span class="fe fe-video"></span> Stream</a>
          </div>
        </li>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Map
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="<%= maps_path %>"><span class="fe fe-clock"></span> History</a>
          <a class="dropdown-item" href="<%= maps_path + "/current" %>"><span class="fe fe-map"></span> Live Map</a>
        </div>
      </li>

    <% end %>
    </ul>
    <div class="btn-group dropleft float-right mr-4">
      <% if user_signed_in? %>
      <button type="button" class="btn btn-outline-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <strong><%= current_user.username %></strong>
      </button>
      <div class="dropdown-menu">
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'dropdown-item' %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'dropdown-item'  %>
      </div>
      <% else %>
      <button type="button" class="btn btn-outline-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="fe fe-user"></span> Account
      </button>
      <div class="dropdown-menu">
        <%= link_to "Login", new_user_session_path, :class => 'dropdown-item'  %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'dropdown-item'  %>
      </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_sidebar.html.erb
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
  <div class="sidebar-sticky">
    <ul class="nav flex-column">
      <li class="nav-item">
        <a class="nav-link <% if current_page?(root_url)  then %>
          active
          <% end %>" href="<%= root_path %>">
          <span class="fe fe-activity"></span>
          Dashboard
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link <% if @sensors.present? then %>
          active
          <% end %>" href="<%= sensors_path %>">
          <span class="fe fe-bell"></span>
          Sensors <span class="sr-hard-drive"></span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link <% if @contacts.present? then %>
          active
          <% end %>" href="<%= contacts_path %>">
          <span class="fe fe-phone"></span>
          Contacts <span class="sr-hard-drive"></span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link <% if @videos.present? then %>
          active
          <% end %>" href="<%= videos_path %>">
          <span class="fe fe-video"></span>
          Footage
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link <% if current_page?(maps_path) then %>
          active
          <% end %>" href="<%= maps_path %>">
          <span class="fe fe-map"></span>
          Maps
        </a>
      </li>
    </ul>

    <!-- <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
      <span>Saved reports</span>
      <a class="d-flex align-items-center text-muted" href="#" aria-label="Add a new report">
        <span class="fe fe-plus"></span>
      </a>
    </h6> -->
    <ul class="nav flex-column mb-2">
    </ul>
  </div>
</nav>