config/routes.rb
Rails.application.routes.draw do



  resources :contacts
  resources :streams
  resources :maps do
    get 'current', on: :collection
  end

  resources :videos

  resources :sensors do
   resources :values do
     get 'current', on: :collection
   end
  end

  resources :sensor_types do
    resources :sensors do
  	 resources :values
    end
  end

  #devise routes
  devise_for :users

  # root route
  root 'welcome#index'
end

app/models/sensor.rb
class Sensor < ApplicationRecord
	include ActiveStorageSupport::SupportForBase64
	has_many :values, dependent: :destroy
	has_one_base64_attached :image
end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  before_action :set_sensor, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /sensors
  # GET /sensors.json
  def index
    @sensors = Sensor.all
  end

  # GET /sensors/1
  # GET /sensors/1.json
  def show
    @values = Value.where(sensor_id: @sensor).paginate(:page => params[:page], :per_page => 30).order(id: :desc)
    @bootstrap_paginate_renderer = bootstrap_paginate_renderer
    if @sensor.sensor_type == "GPS" then

        @maps = Map.paginate(:page => params[:page], :per_page => 200).order(id: :desc)
    end
  end

  # GET /sensors/new
  def new
    @sensor = Sensor.new
  end

  # GET /sensors/1/edit
  def edit
  end

  # POST /sensors
  # POST /sensors.json
  def create
    @sensor = Sensor.new(sensor_params)

    respond_to do |format|
      if @sensor.save
        format.html { redirect_to @sensor, notice: 'Sensor was successfully created.' }
        format.json { render :show, status: :created, location: @sensor }
      else
        format.html { render :new }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sensors/1
  # PATCH/PUT /sensors/1.json
  def update
    print "testing!!!!"
    respond_to do |format|
      if @sensor.update(sensor_params)
        format.html { redirect_to @sensor, notice: 'Sensor was successfully updated.' }
        format.json { render :show, status: :ok, location: @sensor }
        format.js # render values
      else
        format.html { render :edit }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sensors/1
  # DELETE /sensors/1.json
  def destroy
    @sensor.destroy
    respond_to do |format|
      format.html { redirect_to sensors_url, notice: 'Sensor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sensor
      @sensor = Sensor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sensor_params
      params.require(:sensor).permit(:name, :value, :image, :description,:sensor_type)
    end
end

app/views/sensors/_form.html.erb
<%= form_with(model: sensor, local: true) do |form| %>
  <% if sensor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sensor.errors.count, "error") %> prohibited this sensor from being saved:</h2>

      <ul>
      <% sensor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text">Image</span>
  </div>
  <div class="custom-file">
    <input type="file" class="" id="">
    <%= form.file_field :image, :class => "custom-file-input" %>
    <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
  </div>
  </div>
  <div class="form-group">
    <%= form.label :sensor_type %>
    <%= form.select :sensor_type, options_for_select([['GPS','GPS'],['AXIS','AXIS'],['VALUE','VALUE'],['CONTROL','CONTROL']])  ,:class =>"form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name,:class =>"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description,:class =>"form-control" %>
  </div>
  <div class="actions">
    <%= form.submit 'submit',:class =>"btn btn-primary" %>
  </div>
<% end %>

app/views/sensors/edit.html.erb
<%= render partial: "shared/header", locals: {title: "Editing Sensor" , back: sensors_path, single_page: @sensor} %>
<%= render 'form', sensor: @sensor %>

app/views/sensors/index.html.erb
<%= render partial: "shared/header", locals: {title: "Sensors" , back: root_path,single_page: "", new_page: new_sensor_path} %>


<div class="container">
      <% if not @sensors.any? then  %>
      <div class="py-5">
        <div class="d-flex  justify-content-center row py-5">
          <h4 class="text-secondary">
            You haven't created any Sensors
          </h4>
        </div>
        <div class="d-flex  justify-content-center row">
         <%= link_to 'Create New Sensor Now', new_sensor_path, :class => "btn btn-sm btn-outline-primary" %>
        </div>
      </div>
      <% end %>
      <div class="row">
        <% @sensors.each do |sensor| %>
        <div class="col-md-4">
          <div class="<% if sensor.sensor_type == "CONTROL" then %> switches <% end %> card mb-4 shadow-sm">
            <% if sensor.sensor_type == "CONTROL" then %>
              <!-- no image thing -->
            <% else %>
              <% if sensor.image.attached? then %>
                <%= image_tag(sensor.image, style:'width:100%; height:auto')%>
              <% else %>
                <svg class="bd-placeholder-img card-img-top" width="100%" height="300px" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title><%= sensor.name %></title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em"><%= sensor.name.capitalize   %> No Image</text></svg>
              <% end %>
            <% end %>
            <div class="card-body">
              <p class="card-text">
                <b><%= sensor.name %></b><br/>
                <%= sensor.description.capitalize %>
              </p>
              <% if sensor.sensor_type == "CONTROL" then %>
                <div class='ioButton' >
                 <input id="value" type="text" hidden value="0">
               </div>
               <br>
              <% end %>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <%= link_to 'Show', sensor, :class => "btn btn-sm btn-outline-secondary" %>
                  <%= link_to 'Edit', edit_sensor_path(sensor), :class => "btn btn-sm btn-outline-secondary" %>
                  <%= link_to 'Destroy', sensor, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-sm btn-outline-secondary" %>
                </div>
                <% if sensor.sensor_type == "GPS" then %>
                  <small class="text-muted"><%= Map.count %> entery</small>
                <% else %>
                  <small class="text-muted"><%= sensor.values.count %> entery</small>
                <% end %>
              </div>
            </div>
          </div>
        </div>


        <% if (sensor.sensor_type == "CONTROL") then %>
        <script type="text/javascript">
        	$(".ioButton").click(function(){
        		var currentButton = $(this);
        		currentButton.addClass("awaitStatus");
        		jQuery.ajax({
        			url: "<%= sensor_path(sensor)+"/values.json" %>",
        			type: "POST",
        			data: {"value":{"json":"1"}},
        			dataType: "json",
        			beforeSend: function(x) {
        				if (x && x.overrideMimeType) {
        					x.overrideMimeType("application/j-son;charset=UTF-8");
        				}
        			},
        			success: function(result) {
                setTimeout(
                function()
                {
                  $.getJSON('<%= sensor_path(sensor)+"/values/current.json" %>', function(result) {
                    var val = result.json;
                    $("#value").val(val);
                    currentButton.removeClass('awaitStatus');
                    currentButton.removeClass('statusSuccess');
                    currentButton.removeClass('statusError');
                    if(val == 0){
                      currentButton.addClass('statusSuccess');
                    }else{
                      currentButton.addClass('statusError');
                    }
                  });
                }, 5000);
        			}
        			});
              // it should go down to zero if it was successful (from the hardware)
        	});
        </script>
        <% end %>
        <% end %>
      </div>
    </div>

app/views/sensors/new.html.erb
<%= render partial: "shared/header", locals: {title: "New Sensor" , back: sensors_path, single_page: ""} %>
<%= render 'form', sensor: @sensor %>